#!/usr/bin/env python3
"""
ATTOM API
https://api.developer.attomdata.com
"""

ADDRESSES = [
  "266 ANN ST, CLARENDON HILLS, IL 60514",
  "546 PAMELA CIR, HINSDALE, IL 60521",
  "923 LAWN CIR, WESTERN SPRINGS, IL 60558",
  "6474 BIG BEAR DR, INDIAN HEAD PARK, IL 60525",
  "5405 FRANKLIN AVE, WESTERN SPRINGS, IL 60558",
  "4036 HOWARD AVE, WESTERN SPRINGS, IL 60558",
  "908 S THURLOW ST, HINSDALE, IL 60521"
]

CLARENDON_HILLS = "CLARENDON HILLS, IL"

SOLD_ADDRESSES_FOR_AVM = {
  "7 TUTTLE AVE" : CLARENDON_HILLS,
  "266 WOODSTOCK AVE": CLARENDON_HILLS,
  "18 TUTTLE AVE": CLARENDON_HILLS,
  "141 WOODSTOCK AVE": CLARENDON_HILLS,
  "155 CHICAGO AVE": CLARENDON_HILLS,
  "25 CHESTNUT AVE": CLARENDON_HILLS,
  "31 OXFORD AVE": CLARENDON_HILLS,
  "124 BYRD CT": CLARENDON_HILLS,
  "14 WOODSTOCK AVE": CLARENDON_HILLS,
  "35 WOODSTOCK AVE": CLARENDON_HILLS,
  "12 GILBERT AVE": CLARENDON_HILLS,
  "12 N PROSPECT AVE": CLARENDON_HILLS,
  "211 S PROSPECT AVE": CLARENDON_HILLS,
  "6 N PROSPECT AVE": CLARENDON_HILLS,
  "7 WOODSTOCK AVE": CLARENDON_HILLS,
  "2 TUTTLE AVE": CLARENDON_HILLS,
  "24 MCINTOSH AVE": CLARENDON_HILLS,
  "35 ARTHUR AVE": CLARENDON_HILLS,
  "366 RUBY AVE": CLARENDON_HILLS,
  "222 HOLMES AVE": CLARENDON_HILLS,
  "224 HOLMES AVE": CLARENDON_HILLS,
  "220 WALKER AVE": CLARENDON_HILLS,
  "208 WALKER AVE": CLARENDON_HILLS,
  "254 ANN ST": CLARENDON_HILLS,
  "250 ANN ST": CLARENDON_HILLS,
  "50 SHORT ST": CLARENDON_HILLS,
  "52 SHORT ST": CLARENDON_HILLS,
  "229 GRANT AVE": CLARENDON_HILLS,
  "231 GRANT AVE": CLARENDON_HILLS,
  "221 GRANT AVE": CLARENDON_HILLS,
  "210 GRANT AVE": CLARENDON_HILLS,
  "47 HARRIS AVE": CLARENDON_HILLS,
  "352 HARRIS AVE": CLARENDON_HILLS,
  "349 RIDGE AVE": CLARENDON_HILLS,
  "429 COLFAX AVE": CLARENDON_HILLS,
  "307 PARK AVE": CLARENDON_HILLS,
  "352 WESTERN AVE": CLARENDON_HILLS,
  "402 WESTERN AVE": CLARENDON_HILLS
}